### ISSUE TITLE
add to idyll example gallery

### ISSUE THREAD

**Issue by mathisonian** [eutopi/bkt_interactive#1]
Hi @eutopi,

I just stumbled across your repo looking at idyll's network graph, very cool work! I wonder if you would be open to us including this on Idyll's example gallery?

Best,
Matt

**Comment by eutopi** [comment]
Hi @mathisonian,

Definitely! Thank you so much for creating such a clean tool--had lots of fun using it! :)

> Hi @eutopi,
> 
> I just stumbled across your repo looking at idyll's network graph, very cool work! I wonder if you would be open to us including this on Idyll's example gallery?
> 
> Best,
> Matt

**Comment by mathisonian** [comment]
Thanks @eutopi! This is now up on https://idyll-lang.org/gallery
